### ISSUE TITLE
Reduce node.js dependency to 12.16.0 [EDITED]

### ISSUE THREAD

**Issue by Zloka** [akauppi/firebase-jest-testing#4] opened 2020-09-12 14:52 UTC
Tried adding `firebase-jest-testing` as a dev-dependency of one of my own projects.

My steps were:

1. Add a `.yarnrc` file with `registry "https://npm.pkg.github.com/akauppi"` defined in it.
2. Run `yarn add --dev @akauppi/firebase-jest-testing@alpha --verbose`

This yields the following output:
```
[1/4] 🔍  Resolving packages...
verbose 0.714 Performing "GET" request to "https://npm.pkg.github.com/akauppi/@akauppi%2ffirebase-jest-testing".
verbose 0.956 Request "https://npm.pkg.github.com/akauppi/@akauppi%2ffirebase-jest-testing" finished with status code 401.
verbose 0.968 Error: Couldn't find package "@akauppi/firebase-jest-testing" on the "npm" registry.
```

Not sure about the final error message, "couldn't find", as the earlier status code (401) indicates that the request was"unauthorized" rather than "not found".

**Comment by akauppi** [comment] 2020-09-15 14:57
How is it with `beta.2`?

**Comment by Zloka** [comment] 2020-09-25 12:44
Seems to work. However, it complains about the `node` engine version. I'm developing on a quite old version (`10.20.1`) and it seems top require >=14.3.

I can try upgrading, but I'll have to verify that it doesn't break something else, since we lock in on the same `node` version within our team as a part of having as similar dev environments as possible 🙂

**Comment by akauppi** [comment] 2020-09-26 18:06
I thought I could maybe downgrade to node.js 12 but that's a "no".

Reasons:

- Using ES modules with Jest already requires `--experimental-vm-modules` flag so I would claim that even the latest stable Node is not "recent enough". :)

The raison d'etre of the repo is for testing the readiness of Jest for ES modules - only development.

---

Edit: That was a bit hasty. According to [this](https://stackoverflow.com/questions/60372790/node-v13-jest-es6-native-support-for-modules-without-babel-or-esm#answer-61653104), `^12.16.0` would be okay.

I'd suggest I have a look at it when making a CI / Docker image for the repo. That would allow my development machine to use the latest Node.js but the image would check things work with the 12 season. How does that sound?

**Comment by Zloka** [comment] 2020-09-27 05:50
That does sound great! :) I should probably upgrade to a version at or above that anyhow.

**Comment by akauppi** [comment] 2020-09-28 06:53
So: no estimates on delivery but the aim is to support 12.16.0. Let's keep the issue open for that. (I may edit its title to be more timely).

**Comment by akauppi** [comment] 2021-03-03 09:37
I'm afraid this is likely not going to happen. Firebase now supports node 14 and I'm on node 15.

The issue is not that it cannot be done; it's about continuing testing that it remains working, and I haven't even gotten to setting up the CI. So.. closing. @Zloka if you wish to take it and make a PR, it's all yours!

**Closed as completed by akauppi** 2021-03-03 09:37 UTC
Labels: enhancement, backburner

**Comment by Zloka** [comment] 2021-03-03 09:53
I see @akauppi, as you've probably noticed I haven't had any time to look into it either. Perhaps we'll revisit some other time! :)
